apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: luyanbo-opensergo-sca
  labels:
    app: luyanbo-opensergo-sca
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luyanbo-opensergo-sca
  template:
    metadata:
      labels:
        app: luyanbo-opensergo-sca
    spec:
      containers:
        - name: luyanbo-opensergo-sca
          image: registry.cn-huhehaote.aliyuncs.com/luyanbo-msc/opensergo-sca:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9991
          resources:
            limits:
              cpu: "500m"