server:
  port: 9991


spring:
  application:
    name: "example-spring-cloud"
  cloud:
    nacos:
      discovery:
        server-addr: mse-xxxxx-p.nacos-ans.mse.aliyuncs.com:8848
        enable: false
  endpoint:
    info:
      enabled: true
    web:
      exposure:
        include: "*"